//========================
// - Info -
// - about -
// - File -
// - Author : juju80gen -
//========================
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#include "../include/defs.h"
#include "../include/common.h"
#include "../include/gen_code.h"
#include "../include/y.tab.h" // automatically generated by yacc


// PROTOTYPES NEEDED BY MAIN FUNCTION (defined by auto-generated files)
int yyparse(node_t * program_root);
extern FILE* yyin;
extern int yylex_destroy(void);

#if YYDEBUG
extern int yydebug;
#endif

int yywrap(void) 
{
    return 1;
}


// PROGRAM ENTRY POINT
int main(int argc, char ** argv) 
{
    node_t program_root;
    parse_args(argc, argv);
    yyin = fopen(g_infile, "r");
    if(yyin != NULL)
    {
#if LEX_DEBUG
        while(yylex());
        fclose(yyin);
#else
    #if YYDEBUG
            yydebug = 1;
    #endif
        yyparse(&program_root);
        fclose(yyin);
        run_translation(program_root);
#endif
    }
    else
    {
        printf(RED "Error : " NC "could not open file %s\n", g_infile);
        exit(EXIT_FAILURE);
    }
    yylex_destroy();
    return 0;
}
